"""Final minimal-logo assets. Elephant = the pack's vector (path start moved from x97 to x77
# Regenerates public/brand/minimal/*.svg: pip install fonttools uharfbuzz, run from this folder, copy out/*.svg across.
so it no longer closes with a stray sliver on the ear), eye cut out (evenodd) so the surface
shows through. Wordmark = Fredoka Bold outlines, -0.02em, proportioned from the concept."""
import json, subprocess, os
MX, MY, MW, MH = 27.0, 17.84, 262.31, 232.16
HEAD = ("M77 39C60 36 27 65 27 105c0 35 25 63 55 66 20 2 36-7 47-22 8 27 29 48 56 52 22 3 38-5 52-22 12-15 16-36 14-57 "
        "28-12 43-35 37-61-6-28-32-45-58-43-24 2-42 17-50 38-21-11-49-10-67 0-9-10-21-16-36-17z"
        "M163 105a8 8 0 1 0 16 0a8 8 0 1 0-16 0z")
TRUNK = "M145 137c-2 29 1 59 17 82 14 21 32 31 54 31 31 0 55-24 54-51 0-12-9-20-19-20-10 0-18 7-19 17-1 11-8 17-18 15-19-3-26-27-26-57z"
TRACK, CAP, GAP = -0.02, 0.52, 0.13
size = CAP * MH / 0.700; x0 = MW + GAP * MH; base = 0.77 * MH
j = json.loads(subprocess.check_output(["python3", os.path.join(os.path.dirname(__file__), "wordmark.py"), str(size), "0", str(base), str(TRACK)]))
xmin, ymin, xmax, ymax = j["bbox"]; shift = round(x0 - xmin, 1)
W = round(x0 + (xmax - xmin), 1); H = round(max(MH, ymax), 1)
mark_g = f'<g transform="translate({-MX} {-MY})"><path fill-rule="evenodd" d="{HEAD}"/><path d="{TRUNK}"/></g>'
word = f'<path transform="translate({shift} 0)" d="{j["d"]}"/>'
os.makedirs("out", exist_ok=True)
def svg(vb, body, fill, title="MegaDeal"):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-label="{title}"><g fill="{fill}">{body}</g></svg>\n'
for name, fill in (("purple", "#6520B5"), ("white", "#FFFFFF")):
    open(f"out/megadeal-logo-minimal-{name}.svg", "w").write(svg(f"0 0 {W} {H}", mark_g + word, fill))
    open(f"out/megadeal-elephant-minimal-{name}.svg", "w").write(svg(f"0 0 {round(MW,1)} {round(MH,1)}", mark_g, fill, "MegaDeal elephant"))
# Square icon for review only: white elephant centred on a purple rounded square.
S = 300; scale = 0.74 * S / max(MW, MH); tx = (S - MW * scale) / 2; ty = (S - MH * scale) / 2
icon_body = f'<rect width="{S}" height="{S}" rx="60" fill="#6520B5"/><g transform="translate({tx:.1f} {ty:.1f}) scale({scale:.4f})" fill="#FFFFFF">{mark_g}</g>'
open("out/megadeal-icon-minimal.svg", "w").write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" role="img" aria-label="MegaDeal">{icon_body}</svg>\n')
json.dump({"W": W, "H": H, "MW": round(MW, 1), "MH": round(MH, 1), "MX": MX, "MY": MY, "head": HEAD, "trunk": TRUNK, "word": j["d"], "shift": shift}, open("out/paths.json", "w"))
print("logo viewBox", W, H, "ratio", round(W / H, 3))
# The same shapes for components/BrandLogo.tsx (copy out/logoPaths.ts to components/brand/).
open("out/logoPaths.ts", "w").write(f'''// GENERATED by design/logo-minimal/tools/final.py — the same shapes as
// public/brand/minimal/megadeal-logo-minimal-*.svg. Edit the generator, not this file.

/** The whole lockup's box: elephant, gap, "MegaDeal". */
export const LOGO_VIEWBOX = {{ width: {W}, height: {H} }};
/** The elephant alone (it starts at 0,0 of the lockup). */
export const MARK_VIEWBOX = {{ width: {round(MW, 1)}, height: {round(MH, 1)} }};
/** Moves the pack's elephant coordinates to 0,0. */
export const MARK_TRANSFORM = "translate({-MX} {-MY})";
/** Head and ears, with the eye cut out (fill-rule evenodd), so whatever
 *  the logo sits on shows through the eye. */
export const MARK_HEAD = "{HEAD}";
export const MARK_TRUNK = "{TRUNK}";
/** "MegaDeal" in Fredoka Bold (the site's Fredoka 700), as outlines, so it
 *  looks the same whether or not the web font has loaded. */
export const WORDMARK_TRANSFORM = "translate({shift} 0)";
export const WORDMARK = "{j["d"]}";
''')
