"""Final minimal-logo assets, matched to the approved concept (../concept-reference.png).
Elephant = traced from the concept (trace.py -> elephant-traced.json); the eye is a hole
(evenodd) so the surface shows through. Wordmark = Fredoka Bold outlines (wordmark.py).
Proportions measured from the concept, as fractions of the elephant's height: tallest letter
0.528, baseline 0.768 down from the elephant's top, gap 0.154, wordmark width ~3.19.
Regenerates public/brand/minimal/*.svg and components/brand/logoPaths.ts:
pip install fonttools uharfbuzz; run from this folder; copy out/*.svg and out/logoPaths.ts across."""
import json, subprocess, os
E = json.load(open(os.path.join(os.path.dirname(__file__), "elephant-traced.json")))
MARK, MW, MH = E["d"], E["w"], E["h"]
TRACK, TALL, BASE, GAP = -0.01, 0.528, 0.768, 0.154
def word(size):
    return json.loads(subprocess.check_output(["python3", os.path.join(os.path.dirname(__file__), "wordmark.py"),
                                                str(size), "0", str(BASE * MH), str(TRACK)]))
j = word(100.0)                                    # measure, then size so the tallest letter is TALL * MH
size = 100.0 * TALL * MH / (BASE * MH - j["bbox"][1])
j = word(size)
xmin, ymin, xmax, ymax = j["bbox"]
x0 = MW + GAP * MH; shift = round(x0 - xmin, 1)
W = round(x0 + (xmax - xmin), 1); H = round(max(MH, ymax), 1)
mark = f'<path fill-rule="evenodd" d="{MARK}"/>'
wordp = f'<path transform="translate({shift} 0)" d="{j["d"]}"/>'
os.makedirs("out", exist_ok=True)
def svg(vb, body, fill, title="MegaDeal"):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-label="{title}"><g fill="{fill}">{body}</g></svg>\n'
for name, fill in (("purple", "#6520B5"), ("white", "#FFFFFF")):
    open(f"out/megadeal-logo-minimal-{name}.svg", "w").write(svg(f"0 0 {W} {H}", mark + wordp, fill))
    open(f"out/megadeal-elephant-minimal-{name}.svg", "w").write(svg(f"0 0 {MW} {MH}", mark, fill, "MegaDeal elephant"))
# Square icon for review only: white elephant centred on a purple rounded square.
S = 300; scale = 0.74 * S / max(MW, MH); tx = (S - MW * scale) / 2; ty = (S - MH * scale) / 2
icon_body = f'<rect width="{S}" height="{S}" rx="60" fill="#6520B5"/><g transform="translate({tx:.1f} {ty:.1f}) scale({scale:.4f})" fill="#FFFFFF">{mark}</g>'
open("out/megadeal-icon-minimal.svg", "w").write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" role="img" aria-label="MegaDeal">{icon_body}</svg>\n')
print("logo viewBox", W, H, "ratio", round(W / H, 3), "word width/MH", round((xmax - xmin) / MH, 2))
open("out/logoPaths.ts", "w").write(f'''// GENERATED by design/logo-minimal/tools/final.py — the same shapes as
// public/brand/minimal/megadeal-logo-minimal-*.svg. Edit the generator, not this file.

/** The whole lockup's box: elephant, gap, "MegaDeal". */
export const LOGO_VIEWBOX = {{ width: {W}, height: {H} }};
/** The elephant alone (it starts at 0,0 of the lockup). */
export const MARK_VIEWBOX = {{ width: {MW}, height: {MH} }};
/** The elephant, traced from the approved concept: ears, head and trunk,
 *  with the eye cut out (fill-rule evenodd), so whatever the logo sits on
 *  shows through the eye. */
export const MARK = "{MARK}";
/** "MegaDeal" in Fredoka Bold (the site's Fredoka 700), as outlines, so it
 *  looks the same whether or not the web font has loaded. */
export const WORDMARK_TRANSFORM = "translate({shift} 0)";
export const WORDMARK = "{j["d"]}";
''')
